alias cleancrash='sudo rm /var/crash/*'
alias clock='TZ="Spain" date && date'
alias screenshot='gnome-screenshot --interactive &'
alias logout='openbox --exit'
alias houdini='cd /opt/hfs16.5.439/bin && ./hindie &'
